version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: foodflex_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodflex
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - foodflex_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: foodflex_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - foodflex_network

volumes:
  mysql_data:

networks:
  foodflex_network:
    driver: bridge 